# -*- coding: utf-8 -*-
"""
/***************************************************************************
 EasyFilterDockWidget
                                 A QGIS plugin
 Select features by list of values
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-10-03
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Łukasz Świątek
        email                : lukasz.swiatek1996@mial.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal
from qgis.PyQt.QtWidgets import QLineEdit, QComboBox, QPushButton, QHBoxLayout, QSizePolicy, QSpacerItem

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'easy_filter_and_selection_dockwidget_base.ui'))


class EasyFilterDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(EasyFilterDockWidget, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        # --- UX Improvements: Search Bars ---
        self.lineEdit_layer_search = QLineEdit(self)
        self.lineEdit_layer_search.setPlaceholderText("Search layer...")
        # Insert after label (index 1)
        self.verticalLayout_2.insertWidget(1, self.lineEdit_layer_search)

        self.lineEdit_field_search = QLineEdit(self)
        self.lineEdit_field_search.setPlaceholderText("Search field...")
        # Insert after label (index 1)
        self.verticalLayout_5.insertWidget(1, self.lineEdit_field_search)

        # --- Features: Selection Modes & File Import ---
        self.comboBox_selection_mode = QComboBox(self)
        self.comboBox_selection_mode.addItems([
            "New selection", 
            "Add to current", 
            "Remove from current", 
            "Intersect with current"
        ])
        
        self.pushButton_LoadFile = QPushButton("Load from file (txt/csv/xlsx)", self)

        # Insert into verticalLayout_4 (Select/Reverse Select layout)
        # We put them at the top of this layout
        self.verticalLayout_4.insertWidget(0, self.comboBox_selection_mode)
        self.verticalLayout_4.insertWidget(1, self.pushButton_LoadFile)

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
